# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-13 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20180113_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemgroup',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
