# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-13 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_itemgroup_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemgroup',
            name='description',
            field=models.TextField(blank=True, help_text='optional', max_length=200),
        ),
    ]
