# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-13 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_itemgroup_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemgroup',
            name='all_time_available',
            field=models.BooleanField(default=0),
        ),
    ]
