# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_itemgroup_all_time_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemgroup',
            name='group_image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
