# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-25 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_auto_20180124_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemgroup',
            name='group_image',
            field=models.FileField(blank=True, null=True, upload_to='group/'),
        ),
        migrations.AlterField(
            model_name='itemstock',
            name='item_image',
            field=models.FileField(blank=True, null=True, upload_to='items/'),
        ),
    ]
