# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-13 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('dealer_name', models.CharField(max_length=100)),
                ('dealer_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
    ]
