# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 13:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_itemgroup_all_time_available'),
        ('accounts', '0008_auto_20180117_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_reseller', models.BooleanField(default=False)),
                ('new_customer', models.BooleanField(default=False)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('booking_date', models.DateField(default=datetime.date.today)),
                ('tracking_id', models.CharField(blank=True, max_length=100)),
                ('qty', models.IntegerField(default=False)),
                ('order_status', models.CharField(choices=[('P', 'Pre-Booked'), ('B', 'Booked'), ('D', 'Dispatched'), ('R', 'Delivered'), ('C', 'Cancelled')], max_length=10)),
                ('client_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ClientType')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer')),
                ('dealer_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Dealer')),
                ('reseller', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Reseller')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.ItemType')),
            ],
        ),
    ]
