# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 14:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_salesorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='created',
            field=models.DateField(default=datetime.datetime(2018, 1, 17, 14, 0, 32, 625990, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='modified',
            field=models.DateField(default=datetime.datetime(2018, 1, 17, 14, 0, 32, 626031, tzinfo=utc)),
        ),
    ]
