# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20180117_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='reseller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Reseller'),
        ),
    ]
