# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-21 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180117_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
